#!/usr/bin/env node
/**
 * generate-globals.mjs — projects the site's content model into Payload globals.
 *
 * The model comes from ../tools/cms-config.js, the same function that prints
 * the Decap config. Page order, section names taken from headings and field
 * labels taken from English values are therefore identical in both editors,
 * and neither can drift from the templates: add a {{i18n:}} placeholder, run
 * the build, and the key appears in both.
 *
 * Payload differs from Decap in the way that made this worth trying. Decap has
 * no concept of a translation, so the site needs three parallel collections and
 * 2,604 field definitions to describe 950 strings. Payload marks a field
 * `localized` and stores every locale behind it: the same content is 950 fields
 * with a language switcher above them.
 *
 * ## Why a global per section, not per page
 *
 * The obvious shape is one global per page, sections as groups inside it. It
 * does not work, and the reason is worth writing down because it is invisible
 * until the data is real.
 *
 * Payload stores a group's fields as columns on the parent table, and a
 * localized global keeps them in a companion `_locales` table. Reading one back
 * builds a relational sub-select of the form
 *
 *     json_group_array(json_array("col1", "col2", ..., "_locale"))
 *
 * with one argument per column. Postgres caps function arguments at 100
 * (FUNC_MAX_ARGS, a compile-time constant — error 54023), SQLite at 127. The
 * homepage has 183 translatable strings, so as a single global it cannot be
 * read back at all, on either database. No setting lifts the cap.
 *
 * A section is the natural unit below a page and the widest is 42 fields, which
 * leaves comfortable headroom. It also reads better: the sidebar groups each
 * page's sections under the page name, so a page is a table of contents rather
 * than one 183-field form.
 *
 * Output is generated, gitignored and rewritten on every dev/build.
 */

import fs from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'

const dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(dirname, '..', '..')
const OUT = path.resolve(dirname, '..', 'src', 'globals.generated.ts')

const require = createRequire(import.meta.url)
const { buildModel, hintFor, TEXTAREA_OVER } = require(path.join(ROOT, 'tools', 'cms-config.js'))

/** Mirrors build.js — index-print is English only. */
const DEFAULT_LOCALE_ONLY = new Set(['index-print.html'])

/**
 * Content keys are [a-z0-9-]; Payload field names become SQL columns, where a
 * hyphen is not valid unquoted. Underscore never appears in a content key, so
 * the swap is reversible exactly — which is what lets the build turn a Payload
 * document back into the `page.section.field` keys the templates use, with no
 * lookup table to keep in step. The guard below is what keeps that true.
 */
const toIdent = (key) => key.replace(/-/g, '_')

/** Postgres truncates identifiers at 63 bytes. `<dbName>_locales` must fit. */
const PG_IDENT_MAX = 63
/** Postgres FUNC_MAX_ARGS. The read builds one argument per column, plus _locale. */
const PG_FUNC_MAX_ARGS = 100

function main() {
  const model = buildModel({
    contentDir: path.join(ROOT, 'content'),
    srcDir: path.join(ROOT, 'src'),
    defaultLocaleOnly: DEFAULT_LOCALE_ONLY,
  })

  const illegal = []
  const tooWide = []
  const tooLong = []
  const seen = new Set()
  let fieldCount = 0

  const L = []
  L.push('// GENERATED by scripts/generate-globals.mjs from ../content/en/ — do not edit.')
  L.push('// Regenerated on every `npm run dev` and `npm run build`.')
  L.push('')
  L.push("import type { GlobalConfig } from 'payload'")
  L.push("import { noMarkup } from './lib/validators'")
  L.push('')

  const entries = []

  for (const page of model) {
    for (const section of page.sections) {
      const slug = `page-${page.name}-${section.name}`
      const dbName = toIdent(slug)
      const varName = toIdent(slug).replace(/^page_/, 'g_')

      if (seen.has(slug)) illegal.push(`duplicate slug ${slug}`)
      seen.add(slug)
      if (section.name.includes('_')) illegal.push(`${page.name}.${section.name}`)
      if (section.fields.length + 1 > PG_FUNC_MAX_ARGS) {
        tooWide.push(`${slug} (${section.fields.length + 1} args)`)
      }
      if (dbName.length + '_locales'.length > PG_IDENT_MAX) {
        tooLong.push(`${dbName}_locales (${dbName.length + 8})`)
      }

      entries.push({ slug, page: page.name, section: section.name, defaultLocaleOnly: page.defaultLocaleOnly })

      L.push(`const ${varName}: GlobalConfig = {`)
      L.push(`  slug: ${JSON.stringify(slug)},`)
      L.push(`  dbName: ${JSON.stringify(dbName)},`)
      L.push(`  label: ${JSON.stringify(section.label)},`)
      // Groups the page's sections together in the sidebar, in page order.
      L.push(`  admin: { group: ${JSON.stringify(page.label)} },`)
      // The site is public; the strings in it are already on the open web. Read
      // stays open so the static build can fetch without holding a credential.
      L.push('  access: { read: () => true },')
      L.push('  fields: [')

      for (const field of section.fields) {
        fieldCount++
        if (field.name.includes('_')) illegal.push(`${page.name}.${section.name}.${field.name}`)

        const hint = hintFor(field.name, section.name, field.value, true)
        const multiline = field.value.length > TEXTAREA_OVER

        L.push('    {')
        L.push(`      type: ${JSON.stringify(multiline ? 'textarea' : 'text')},`)
        L.push(`      name: ${JSON.stringify(toIdent(field.name))},`)
        L.push(`      label: ${JSON.stringify(field.label)},`)
        // Every string on the site is translatable; nothing is shared between
        // locales, so localized is unconditional.
        L.push('      localized: true,')
        L.push('      validate: noMarkup,')
        if (hint) L.push(`      admin: { description: ${JSON.stringify(hint)} },`)
        L.push('    },')
      }

      L.push('  ],')
      L.push('}')
      L.push('')
    }
  }

  const fatal = [
    ...illegal.map((k) => `content key contains "_" or collides: ${k}`),
    ...tooWide.map((k) => `section exceeds the ${PG_FUNC_MAX_ARGS}-argument read limit: ${k}`),
    ...tooLong.map((k) => `identifier exceeds Postgres' ${PG_IDENT_MAX} bytes: ${k}`),
  ]
  if (fatal.length) {
    console.error('ERROR: the content model does not fit the database:')
    fatal.forEach((k) => console.error('  ' + k))
    process.exit(1)
  }

  L.push('export const pageGlobals: GlobalConfig[] = [')
  for (const e of entries) L.push(`  ${toIdent(e.slug).replace(/^page_/, 'g_')},`)
  L.push(']')
  L.push('')
  L.push('/** What the static build fetches, and the content key each global carries. */')
  L.push('export const SECTIONS = ' + JSON.stringify(entries, null, 2) + ' as const')
  L.push('')

  fs.writeFileSync(OUT, L.join('\n'), 'utf8')

  const pages = new Set(entries.map((e) => e.page))
  const widest = Math.max(...model.flatMap((p) => p.sections.map((s) => s.fields.length)))
  console.log(
    `globals.generated.ts: ${entries.length} globals across ${pages.size} pages, ` +
      `${fieldCount} localized fields (widest section ${widest} fields, cap ${PG_FUNC_MAX_ARGS - 1})`
  )
}

main()
